repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2 # Use the latest stable version
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0 # Use the latest stable version
    hooks:
      - id: flake8
        additional_dependencies: [flake8]

  # Optional: Check for trailing whitespace, end of file, etc.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
