# Generated by Django 5.2.4 on 2025-07-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("sort_order", models.IntegerField(db_index=True, default=0)),
            ],
            options={
                "db_table": "categories",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
