# Generated by Django 5.2.4 on 2025-08-01 02:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        help_text="Rating from 1 to 5",
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="Rating must be at least 1"
                            ),
                            django.core.validators.MaxValueValidator(
                                5, message="Rating cannot exceed 5"
                            ),
                        ],
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Comment content", null=True
                    ),
                ),
                ("comment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        db_column="account_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        db_column="book_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="books.book",
                    ),
                ),
            ],
            options={
                "db_table": "comments",
                "ordering": ["-comment_date"],
                "unique_together": {("account", "book")},
            },
        ),
    ]
