# Generated by Django 5.2.4 on 2025-08-01 02:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
                ("author_name", models.CharField(max_length=255)),
                ("publisher_name", models.CharField(max_length=255, null=True)),
                ("published_date", models.DateField(null=True)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("photo_path", models.CharField(max_length=255, null=True)),
                ("total_rating_value", models.IntegerField(default=0)),
                ("total_rating_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="books",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "db_table": "books",
                "ordering": ["-created_at", "-updated_at"],
                "indexes": [
                    models.Index(fields=["title"], name="books_title_7a737c_idx"),
                    models.Index(
                        fields=["author_name"], name="books_author__de5050_idx"
                    ),
                ],
            },
        ),
    ]
